version: "3.9"

services:
  python-app:
    build:
      context: .
      dockerfile: Py.Dockerfile
    container_name: python-app
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - simple-kong-gateway-network

  go-app:
    build:
      context: .
      dockerfile: Go.Dockerfile
    container_name: go-app
    ports:
      - "8005:8005"
    environment:
      HOST: host.docker.internal
      PORT: 5000
      JWT_SECRET: jwtsecretjwtsecretjwtsecretjwtsecret
      JWT_ISSUER: jwtissuerjwtissuerjwtissuerjwtissuer
      JWT_EXPIRATION: 3600s
    restart: unless-stopped
    networks:
      - simple-kong-gateway-network

networks:
  simple-kong-gateway-network:
    driver: bridge